### ISSUE TITLE
Issus on calling in python

### ISSUE THREAD

**Issue by Cafelatte1** [chaconlab/korpm#2]
Hi, I want to use this amazing architecture for predicting sequence stability !

But I had an error when calling script in python.
I don't know why this occurs (files are properly located in my thought).
Althought I used given files after clone repository, 512 error occurs.
Can you give a help? please refer to below screen shot.

![image](https://user-images.githubusercontent.com/57206771/206905696-efda22bf-7aa5-44ec-80c6-168acb46a51a.png)

**Comment by chaconlab** [comment]
I am not sure but it looks like the potential file is corrupted. Are you
working on Linux?

Pablo




----------------------------------------------------
Pablo Chacón http://chaconlab.org
Biological Physical Chemistry Dept. IQFR <http://www.iqfr.csic.es/>-CSIC
<http://www.csic.es/>
C/Serrano 119, Madrid 28006, Spain.
Phone :(+34) 91 561 9400 #442116
----------------------------------------------------

**Comment by Cafelatte1** [comment]
> I am not sure but it looks like the potential file is corrupted. Are you working on Linux? Pablo
 
Yes ! I am working on Linux (provided OS in Kaggle, Kaggle is AI / DataScience competiton platform)
Shoud I run this model in Window?

**Comment by chaconlab** [comment]
My guess is that the binary format of Kaggle is different from linux (or
the file is corrupted). Sorry, I am not an expert on that...

Do you have a real Linux box around you to check?

Pablo







----------------------------------------------------
Pablo Chacón http://chaconlab.org
Biological Physical Chemistry Dept. IQFR <http://www.iqfr.csic.es/>-CSIC
<http://www.csic.es/>
C/Serrano 119, Madrid 28006, Spain.
Phone :(+34) 91 561 9400 #442116
----------------------------------------------------

**Comment by Cafelatte1** [comment]
> Do you have a real Linux box around you to check?

Unfortunately not T.T
I tried some times more but it didn't work. But it is okay since I've known your architecture from this time :)
I will try some tasks with your model later in real Linux env if there is a chance.

Thanks for your fast reply !

**Comment by pietrosormanni** [comment]
I've got the exact same error (not from python, from zsh terminal on mac using gcc compiled version):

```
korpm-main % sbg/bin/korpm_gcc input.txt --dir Ssym --score_file pot/korp6Dv1.bin -o out.txt 
readKORP> dimensions= 1936876918  cutoff= 0.000  Frame model 104  nb= 1936749684  nb2= 1731145530  use_bonding= 1  bonding_factor= 838775592853885862287507456.000  ngauss= 1731097446  fullgauss= 1  useJI= 1  each_bonding= 1 found in pot/korp6Dv1.bin map.
Please, select a valid frame model! (you've entered 104)
 Forcing exit!
```

**Comment by chaconlab** [comment]
Hi Pietro,

It is a GitHub problem with gzip and with large files:
https://github.com/git-lfs/git-lfs/issues/903
I am trying to fix it, meanwhile, you can either clone the repository with
git or download by hand the two pot files.

Sorry, I did not realize this before (I always cloned..).

All the best,

Pablo








----------------------------------------------------
Pablo Chacón http://chaconlab.org
Biological Physical Chemistry Dept. IQFR <http://www.iqfr.csic.es/>-CSIC
<http://www.csic.es/>
C/Serrano 119, Madrid 28006, Spain.
Phone :(+34) 91 561 9400 #442116
----------------------------------------------------

**Comment by chaconlab** [comment]
Fixed...
