### ISSUE TITLE
trace trap on zsh (Mac OSX korpm_gcc)

### ISSUE THREAD

**Issue by pietrosormanni** [chaconlab/korpm#4]
Hi,
to compile on Mac OSX 13.2 (with M2 chip) I had to use the gcc version and also to remove -lrt from the file objects.mk in folder korpm/Release_gcc
So maybe the above is what causing the error below (albeit it's unlikely):
```
korpm % sbg/bin/korpm_gcc input.txt --dir Ssym --score_file pot/korp6Dv1.bin -o out.txt
readKORP> dimensions= 6  cutoff= 16.000  Frame model 10  nb= 1  nb2= 4  use_bonding= 1  bonding_factor= 1.800  ngauss= 0  fullgauss= 0  useJI= 0  each_bonding= 0 found in pot/korp6Dv1.bin map.
Frame model 10 => 1-frame/aa using CA for distances and N,C for frames
readKORP> Reading raw meshes from pot/korp6Dv1.bin
readKORP> Current potential map is 6D and frame model 10 (parser input overridden by map)
readKORP> S-mapping: 0 -1 1 1 1 0 0 0 0 0
readKORP> F-mapping:   1.00  1.80  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00
readKORP> Reading Bin-wise 6D maps:
energy> Reading potential map [========================================>] 100% Finished!
readKORP> Map reading stuff finished!
Dimensions 6 Cutoff 16.000000 Radial 10 Cells 36 Chis 0 Maps 2
zsh: trace trap  sbg/bin/korpm_gcc input.txt --dir Ssym --score_file pot/korp6Dv1.bin -o 
```

**Comment by chaconlab** [comment]
Thanks, Pietro, I do not have an M1 box. I just removed the -lrt (it is not needed, anyway) 

Pablo

**Comment by pietrosormanni** [comment]
Thank you for your reply. removing -lrt enables to complete the compilation step but then the executables gives the above error. I don't have a linux machine, but does korpm_gcc work on a zsh shell on there?
trace trap is a nasty issue to solve:
https://stackoverflow.com/questions/2611607/are-exc-breakpoint-sigtrap-exceptions-caused-by-debugging-breakpoints

**Comment by chaconlab** [comment]
Hi Pietro,

It works with zsh on linux. On MacOs I suggest using intel compiler (it is
free) and it works (if it is not an M1).
I will investigate some flags on GCC but has not made much sense when I
trace the bug.


Pablo





----------------------------------------------------
Pablo Chacón http://chaconlab.org
Biological Physical Chemistry Dept. IQFR <http://www.iqfr.csic.es/>-CSIC
<http://www.csic.es/>
C/Serrano 119, Madrid 28006, Spain.
Phone :(+34) 91 561 9400 #442116
----------------------------------------------------

**Comment by chaconlab** [comment]
Hi Pietro,

I think I got it, could you test the new version on an M1? 
Thanks

**Comment by pietrosormanni** [comment]
Thank you very much, I've tested it on M2 MacBook Air (just the first command in the readme) and it runs fine reproducing the same DDG number you put in the readme.
