### ISSUE TITLE
Please, select a valid frame model! (you've entered 104)

### ISSUE THREAD

**Issue by moritzburghardt** [chaconlab/korpm#5]
Hi, I am trying to run the example but get the error below - do you know what is the issue?

> readKORP> dimensions= 1936876918  cutoff= 0.000  Frame model 104  nb= 1936749684  nb2= 1731145530  use_bonding= 1  bonding_factor= 838775592853885862287507456.000  ngauss= 1731097446  fullgauss= 1  useJI= 1  each_bonding= 1 found in pot/korp6Dv1.bin map.
Please, select a valid frame model! (you've entered 104)
 Forcing exit!

**Comment by chaconlab** [comment]
I made some small changes for compatibility with OSX, please check again with the new version.

Pablo
