### ISSUE TITLE
Please, select a valid frame model! (you've entered 104)

### ISSUE THREAD

**Issue by kemars** [chaconlab/korpm#6]
I tried your prediction software, however I always get this error:

Please, select a valid frame model! (you've entered 104)

 when i try with my data or your example. I ran your code on Ubuntu with g++, do you have any idea which is the problem.

Thank you

**Comment by chaconlab** [comment]
Hi Marc,

Sorry Marc, I have Ubuntu & g++, and it works fine. Just in case, the first
line should be:
readKORP> dimensions= 6  cutoff= 16.000  Frame model 10  nb= 1  nb2= 4
 use_bonding= 1  bonding_factor= 1.800  ngauss= 0  fullgauss= 0  useJI= 0
 each_bonding= 0 found in pot/korp6Dv1.bin map.
If not, please check the file pot/korp6Dv1.bin it should have 317M.

Pablo







----------------------------------------------------
Pablo Chacón http://chaconlab.org
Biological Physical Chemistry Dept. IQFR <http://www.iqfr.csic.es/>-CSIC
<http://www.csic.es/>
C/Serrano 119, Madrid 28006, Spain.
Phone :(+34) 91 561 9400 #442116
----------------------------------------------------

**Comment by kemars** [comment]
Hi Pablo,

it works now, as you write the map file wasn't well download with git command. I download both by hand and your code works.
Thank you.
